services:
  lizardfs-master:
    environment:
      - ROLE=master
    container_name: lizardfs-master
    hostname: lizardfs-master
    image: lizardfs
    build:
      context: docker/
      dockerfile: Dockerfile
    volumes:
      - ./data/master:/var/lib/mfs
      - ./config:/etc/lizardfs
