services:
  lizardfs-master:
    env_file:
      - .env
    environment:
      - ROLE=master
    container_name: lizardfs-master
    hostname: lizardfs-master
    image: hmknapp/lizardfs
    build:
      context: docker/
      dockerfile: Dockerfile
    volumes:
      - ./data/master:/var/lib/lizardfs
      - ./config:/etc/lizardfs
    restart: unless-stopped

  lizardfs-master-arm32:
    env_file:
      - .env
    environment:
      - ROLE=master
    container_name: lizardfs-master
    hostname: lizardfs-master
    image: hmknapp/lizardfs-arm32
    build:
      context: docker/
      dockerfile: Dockerfile.arm32v7
    volumes:
      - ./data/master:/var/lib/lizardfs
      - ./config:/etc/lizardfs
    restart: unless-stopped

  lizardfs-chunkserver:
    env_file:
      - .env
    environment:
      - ROLE=chunkserver
    container_name: lizardfs-chunkserver
    hostname: lizardfs-chunkserver-${HOSTNAME}
    image: hmknapp/lizardfs
    volumes:
      - ./data/chunkserver:/var/lib/lizardfs
      - ./config:/etc/lizardfs
      - ${LOCAL_MOUNT_ROOT:-/mnt/lizardfs/disks}:/mnt/lizardfs/disks
    restart: unless-stopped

  lizardfs-chunkserver-arm32:
    env_file:
      - .env
    environment:
      - ROLE=chunkserver
    container_name: lizardfs-chunkserver
    hostname: lizardfs-chunkserver-${HOSTNAME}
    image: hmknapp/lizardfs-arm32
    volumes:
      - ./data/chunkserver:/var/lib/lizardfs
      - ./config:/etc/lizardfs
      - ${LOCAL_MOUNT_ROOT:-/mnt/lizardfs/disks}:/mnt/lizardfs/disks
    restart: unless-stopped

  lizardfs-metalogger:
    env_file:
      - .env
    environment:
      - ROLE=metalogger
    container_name: lizardfs-metalogger
    hostname: lizardfs-metalogger-${HOSTNAME}
    image: hmknapp/lizardfs
    volumes:
      - ./data/metalogger:/var/lib/lizardfs
      - ./config:/etc/lizardfs
    restart: unless-stopped

  lizardfs-metalogger-arm32:
    env_file:
      - .env
    environment:
      - ROLE=metalogger
    container_name: lizardfs-metalogger
    hostname: lizardfs-metalogger-${HOSTNAME}
    image: hmknapp/lizardfs-arm32
    volumes:
      - ./data/metalogger:/var/lib/lizardfs
      - ./config:/etc/lizardfs
    restart: unless-stopped

  lizardfs-cgiserver:
    env_file:
      - .env
    environment:
      - ROLE=cgiserver
    container_name: lizardfs-cgiserver
    hostname: lizardfs-cgiserver
    image: hmknapp/lizardfs
    volumes:
      - ./data/metalogger:/var/lib/lizardfs
      - ./config:/etc/lizardfs
    ports:
      - 127.0.0.1:9425:9425
    restart: unless-stopped

  lizardfs-cgiserver-arm32:
    env_file:
      - .env
    environment:
      - ROLE=cgiserver
    container_name: lizardfs-cgiserver
    hostname: lizardfs-cgiserver
    image: hmknapp/lizardfs-arm32
    volumes:
      - ./data/metalogger:/var/lib/lizardfs
      - ./config:/etc/lizardfs
    ports:
      - 127.0.0.1:9425:9425
    restart: unless-stopped

  lizardfs-mount:
    env_file:
      - .env
    environment:
      - ROLE=mount
    container_name: lizardfs-mount
    hostname: lizardfs-mount-${HOSTNAME}
    image: hmknapp/lizardfs
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    ports:
      - 127.0.0.1:22022:22
    restart: unless-stopped

  lizardfs-mount-arm32:
    env_file:
      - .env
    environment:
      - ROLE=mount
    container_name: lizardfs-mount
    hostname: lizardfs-mount-${HOSTNAME}
    image: hmknapp/lizardfs-arm32
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    ports:
      - 127.0.0.1:22022:22
    restart: unless-stopped
